# Generated by Django 5.0.4 on 2026-06-09 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='RWF', max_length=3)),
                ('payment_method', models.CharField(choices=[('mtn-momo', 'MTN Mobile Money'), ('airtel-money', 'Airtel Money'), ('card', 'Credit/Debit Card'), ('bank-transfer', 'Bank Transfer')], max_length=20)),
                ('purpose', models.CharField(choices=[('listing-fee', 'Listing Fee'), ('featured-fee', 'Featured Listing'), ('agent-subscription', 'Agent Subscription'), ('legal-service', 'Legal Service'), ('interior-design', 'Interior Design')], max_length=30)),
                ('transaction_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('momo_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='listings.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
