# Generated by Django 5.0.4 on 2026-06-09 11:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_rw', models.CharField(blank=True, max_length=100)),
                ('name_fr', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(default='other', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'amenities',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('description_fr', models.TextField(blank=True)),
                ('description_rw', models.TextField(blank=True)),
                ('purpose', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('lease', 'For Lease'), ('pg', 'Paying Guest')], max_length=20)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('land', 'Land/Plot'), ('commercial', 'Commercial'), ('office', 'Office Space'), ('warehouse', 'Warehouse'), ('industrial', 'Industrial'), ('hotel', 'Hotel/Resort'), ('farm', 'Farm')], max_length=30)),
                ('furnishing_status', models.CharField(blank=True, choices=[('unfurnished', 'Unfurnished'), ('semi-furnished', 'Semi-Furnished'), ('furnished', 'Furnished')], max_length=20, null=True)),
                ('listing_status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('sold', 'Sold'), ('rented', 'Rented'), ('featured', 'Featured')], default='draft', max_length=20)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('province', models.CharField(choices=[('Kigali', 'Kigali City'), ('Southern', 'Southern Province'), ('Western', 'Western Province'), ('Northern', 'Northern Province'), ('Eastern', 'Eastern Province')], max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('locality', models.CharField(blank=True, max_length=200)),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('full_address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('balconies', models.PositiveIntegerField(default=0)),
                ('total_floors', models.PositiveIntegerField(blank=True, null=True)),
                ('floor_number', models.PositiveIntegerField(blank=True, null=True)),
                ('built_up_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carpet_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plot_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_per_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maintenance_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_price_negotiable', models.BooleanField(default=False)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('facing_direction', models.CharField(blank=True, max_length=20, null=True)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('parking_spaces', models.PositiveIntegerField(default=0)),
                ('is_gated_community', models.BooleanField(default=False)),
                ('has_power_backup', models.BooleanField(default=False)),
                ('has_lift', models.BooleanField(default=False)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='properties/covers/')),
                ('agent_name', models.CharField(blank=True, max_length=100)),
                ('agent_phone', models.CharField(blank=True, max_length=20)),
                ('is_agent_verified', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('favorites_count', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='listings.property')),
            ],
            options={
                'db_table': 'favorites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_cover', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.property')),
            ],
            options={
                'db_table': 'property_images',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=200)),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'property_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('search_params', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_searches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['purpose', 'property_type'], name='properties_purpose_2995ea_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['province', 'city'], name='properties_provinc_d2ca92_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['listing_status'], name='properties_listing_6df685_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'property')},
        ),
        migrations.AlterUniqueTogether(
            name='propertyreview',
            unique_together={('user', 'property')},
        ),
    ]
